### PR TITLE
bug: #99 - Fix currency conversion

### LINKED ISSUE #99: Bug in currency conversion
📋 [2026-03-09T10:33:25.414Z] Ignored comment on issue #97: missing "## Take action" directive
❌ [2026-03-09T10:33:34.584Z] [refactor-the-code-fuyzg6] Failed to fetch exchange rates: TypeError: fetch failed
✅ [2026-03-09T10:33:34.585Z] [refactor-the-code-fuyzg6] Issue cost CSV written: projects/AI_Dev_Workflow/97-refactor-the-code.csv
✅ [2026-03-09T10:33:34.590Z] [refactor-the-code-fuyzg6] Project cost CSV rebuilt: projects/AI_Dev_Workflow/total-cost.csv

### PR DESCRIPTION
**Pull request by paysdoc**
## Summary

Fixes a bug where currency conversion fetch was failing with `TypeError: fetch failed`, causing issues during workflow cost reporting.

- Issue: [#99 - Bug in currency conversion](https://github.com/paysdoc/AI_Dev_Workflow/issues/99)
- ADW Tracking ID: `bug-in-currency-conv-kcbcrp`
- Plan: `specs/issue-99-adw-bug-in-currency-conv-kcbcrp-sdlc_planner-fix-currency-conversion.md`

## What was done

- [x] Added retry logic to currency fetch with configurable attempts
- [x] Added timeout handling to prevent indefinite hangs
- [x] Added fallback mechanism when exchange rate fetch fails
- [x] Updated `costReport.ts` with robust fetch error handling
- [x] Expanded `costReport.test.ts` with tests covering retry, timeout, and fallback scenarios
- [x] Exported updated module from `core/index.ts`

## Key changes

- `adws/core/costReport.ts`: Added retry, timeout, and fallback logic to the currency conversion fetch
- `adws/core/__tests__/costReport.test.ts`: Added test coverage for new retry/timeout/fallback behavior
- `adws/core/index.ts`: Exported `costReport` module
- `adws/phases/workflowCompletion.ts` / `prReviewCompletion.ts`: Minor updates to use improved cost reporting

Closes #99

### CODE REVIEW

File: adws/core/costReport.ts [hunk 1]
```diff
@@ -8,6 +8,15 @@ import { emptyModelUsage } from '../types/costTypes';
 import { log } from './utils';
 import { AgentStateManager } from './agentState';
 
+/** Last-resort fallback EUR/USD rate used when the exchange rate API is unreachable after all retries. */
+const FALLBACK_EUR_RATE = 0.92;
```
Comment (paysdoc) [inline adws/core/costReport.ts:12]: If the rate can be found, update the fallback rate with the latest rate

**Comment by paysdoc** [comment]
## :eyes: Addressing PR Review Comments

Starting automated review of **1** review comment(s).

**ADW ID:** `bug-99-fix-currency-znxk2d`

_Analyzing review feedback..._

---
_Posted by ADW (AI Developer Workflow) automation_

**Comment by paysdoc** [comment]
## :pencil: Planning PR Review Changes

Creating a revision plan based on review feedback...

**ADW ID:** `bug-99-fix-currency-znxk2d`

---
_Posted by ADW (AI Developer Workflow) automation_

**Comment by paysdoc** [comment]
## :white_check_mark: Revision Plan Created

A revision plan has been created to address the review comments.

**ADW ID:** `bug-99-fix-currency-znxk2d`

<details>
<summary>Revision Plan Summary</summary>

Here's a summary of the work done:

- **Analyzed** the PR review comment from `paysdoc` on `adws/core/costReport.ts` line 12, requesting that successful exchange rate fetches update the fallback rate for future use.
- **Read** the original implementation plan, source code, tests, and coding guidelines to understand the full context.
- **Created** the PR review resolution plan at `specs/issue-99-plan.md`.

The plan addresses the review with 6 steps:
1. Add a mutable `lastKnownRates` cache seeded from the immutable `FALLBACK_RATES`
2. Update `fetchExchangeRates()` to write successful rates into `lastKnownRates`
3. Change the fallback path to read from `lastKnownRates` instead of `FALLBACK_RATES`
4. Export a `resetLastKnownRates()` test utility for isolation
5. Add a test verifying that a successful fetch updates the fallback used by subsequent failures
6. Run all validation commands

</details>

---
_Posted by ADW (AI Developer Workflow) automation_

**Comment by paysdoc** [comment]
## :hammer_and_wrench: Implementing Review Changes

Running Build Agent to implement the revision plan...

**ADW ID:** `bug-99-fix-currency-znxk2d`

---
_Posted by ADW (AI Developer Workflow) automation_

**Comment by paysdoc** [comment]
## :white_check_mark: Review Changes Implemented

Changes have been implemented to address the review comments.

**ADW ID:** `bug-99-fix-currency-znxk2d`

<details>
<summary>Implementation Summary</summary>

## Summary

All 6 plan steps implemented with zero regressions:

- **Added `lastKnownRates`** mutable cache in `costReport.ts`, seeded from immutable `FALLBACK_RATES`
- **Updated `fetchExchangeRates()`** success path to write fetched rates into `lastKnownRates`
- **Changed fallback path** to read from `lastKnownRates` instead of `FALLBACK_RATES`
- **Exported `resetLastKnownRates()`** test utility for isolation
- **Added test** verifying successful fetch updates the fallback used by subsequent failures
- **Validation passed**: lint, type-check (both configs), and all 1332 tests green

**Files changed:**
```
adws/core/__tests__/costReport.test.ts | 17 +++++++++++++++++ 
adws/core/costReport.ts                | 11 ++++++++++-
2 files changed, 27 insertions(+), 1 deletion(-)
```

</details>

---
_Posted by ADW (AI Developer Workflow) automation_

**Comment by paysdoc** [comment]
## :test_tube: Running Validation Tests

Running validation tests before pushing changes...

**ADW ID:** `bug-99-fix-currency-znxk2d`

---
_Posted by ADW (AI Developer Workflow) automation_

**Comment by paysdoc** [comment]
## :white_check_mark: All Tests Passed

All validation tests passed!

**ADW ID:** `bug-99-fix-currency-znxk2d`

---
_Posted by ADW (AI Developer Workflow) automation_

**Comment by paysdoc** [comment]
## :floppy_disk: Committing Review Changes

Committing and pushing changes...

**ADW ID:** `bug-99-fix-currency-znxk2d`

---
_Posted by ADW (AI Developer Workflow) automation_

**Comment by paysdoc** [comment]
## :rocket: Changes Pushed

Review changes have been committed and pushed to the branch.

**ADW ID:** `bug-99-fix-currency-znxk2d`

---
_Posted by ADW (AI Developer Workflow) automation_

**Comment by paysdoc** [comment]
## :tada: PR Review Comments Addressed

All **1** review comment(s) have been addressed.

**ADW ID:** `bug-99-fix-currency-znxk2d`

Generated by ADW PR Review workflow

<details>
<summary>Cost Breakdown</summary>

| Model | Input Tokens | Output Tokens | Cache Read | Cache Write | Cost (USD) |
|-------|-------------|---------------|------------|-------------|------------|
| claude-opus-4-6 | 22 | 6,781 | 413,078 | 44,461 | $0.6541 |
| claude-haiku-4-5-20251001 | 66 | 1,886 | 193,349 | 6,220 | $0.0366 |
| **Total** | **88** | **8,667** | **606,427** | **50,681** | **$0.6907** |

**Total Cost:** $0.6907 USD
**Total Cost:** €0.5982 EUR

</details>

---
_Posted by ADW (AI Developer Workflow) automation_
